src/app/routes/index.py
from datetime import datetime
import json

import flask

from mhooge_flask.routing import make_template_context, make_text_response, make_json_response
from mhooge_flask.auth import get_user_details

from core.meta_database import MetaDatabase
from core.log_database import LogDatabase
from core.search import parse_query

page = flask.Blueprint("index", __name__)

@page.route("/")
def index(**project_args):
    if get_user_details() is None:
        return flask.redirect(flask.url_for("login.sign_in"))

    meta_database: MetaDatabase = flask.current_app.config["DATABASE"]
    projects = [x[0] for x in meta_database.get_projects()]

    if "active_project" not in project_args:
        return flask.redirect(flask.url_for("index.project", project_id=projects[0]))

    template_args = {"projects": projects}
    template_args.update(project_args)

    return make_template_context("index.html", 200, **template_args)

@page.route("/<project_id>")
def project(project_id, **project_args):
    if get_user_details() is None:
        return flask.redirect(flask.url_for("login.sign_in"))

    log_database = LogDatabase(project_id)
    log_files = log_database.get_log_files()

    if "active_logfile" not in project_args:
        return flask.redirect(flask.url_for("index.logfile", project_id=project_id, log_id=log_files[0]))

    return index(active_project=project_id, log_files=log_files, **project_args)

@page.route("/<project_id>/<log_id>")
def logfile(project_id, log_id):
    if get_user_details() is None:
        return flask.redirect(flask.url_for("login.sign_in"))

    log_database = LogDatabase(project_id)
    fields = log_database.get_fields(log_id)

    return project(project_id, active_logfile=log_id, log_fields=fields)

@page.route("/<project_id>/<log_id>/search")
def search(project_id, log_id):
    if get_user_details() is None:
        return make_json_response({"results": []}, 401)

    log_database = LogDatabase(project_id)

    results = []

    query = flask.request.args.get("query")
    sql, fields = parse_query(query, log_id)

    results = log_database.search(log_id, sql)

    def stringify_json(elem: dict | list | str | int):
        if isinstance(elem, dict):
            for key in elem:
                elem[key] = stringify_json(elem[key])
            
            return elem
        elif isinstance(elem, list):
            for index in range(len(elem)):
                elem[index] = stringify_json(elem[index])
    
            return elem

        return str(elem)

    def format_row(row):
        return {
            "text": row[0].replace("\n", "<br>"),
            "entry": stringify_json(json.loads(row[1])),
            "date": datetime.fromtimestamp(row[2]).strftime("%Y-%m-%d %H:%M:%S")
        }

    json_response = {
        "results": list(map(format_row, results)),
        "fields": fields
    }

    return make_json_response(json_response, 200)

@page.route("/add", methods=["POST"])
def add_project():
    if get_user_details() is None:
        return make_text_response("Unathorized Access.", 401)

    data = flask.request.form

    meta_database: MetaDatabase = flask.current_app.config["DATABASE"]
    meta_database.add_project(data["project_id"], data["log_path"])

    return flask.redirect(flask.url_for("index.index"))

src/app/routes/login.py
import flask
from mhooge_flask import routing, auth

login_page = flask.Blueprint("login", __name__)

@login_page.route("/", methods=["GET", "POST"])
def sign_in():
    if flask.request.method == "POST":
        # Login attempted.
        data = flask.request.form

        return auth.login(data, "user", "pass", "index.index", "login.html")

    # Display login form.
    return routing.make_template_context("login.html")

src/app/templates/entries.html
{% macro entry(log_entry) -%}

{%- endmacro %}

src/app/templates/head.html
<head>
    <title>Clog{% if project_id %} - {project_id}{% endif %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
	<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>
</head>

src/app/templates/index.html
<!DOCTYPE html>
<html>
{% include 'head.html' %}

<body>
    <div id="content-wrapper">
        <div id="clog-home">
            <a  href="{{ url_for('index.index') }}">Clog</a>
        </div>

        <div id="clog-header">
            <div id="logfile-select-wrapper">
                <p>Log File</p>
                <select id="log-file-select">
                    {% for log_id in log_files %}
                    {% set selected = (not log_id and not loop.index) or (log_id and log_id == active_logfile) %}
                    <option value="{{ log_id }}" {% if selected %}selected {% endif %}onclick="window.location.href='{{ url_for('index.logfile', project_id=active_project, log_id=log_id) }}'">
                        {{ log_id }}.log
                    </option>
                    {% endfor %}
                </select>
            </div>

            {% if active_project %}
            <!-- Fields and search options -->
            <div id="log-search-header">
                {# Included fields
                <div id="included-log-fields" class="log-fields-wrapper">
                    <div class="included-fields-header">
                        <span>Included Fields</span>
                        <div class="show-fields-btn" onclick="toggleShowFields(event.target, 'included-log-fields')">+</div>
                    </div>

                    <div class="log-fields-list d-none">
                        <input id="included-all-check" name="include-all-check" type="checkbox" checked onclick="toggleAllFields(event);">
                        <label for="include-all-check">All</label>

                        <hr>

                        {% for field, count in log_fields %}
                        <div class="log-field-entry included-field" data-field="{{ field }}" data-count="{{ count }}">
                            <input name="{{ field }}_check" type="checkbox" checked onclick="toggleSelectedField(event, 'included-all-check')">
                            <label for="{{ field }}_check">{{ field }} ({{ count }})</label>
                        </div>
                        {% endfor %}
                    </div>
                </div>#}
        
                <input id="text-search" placeholder="Search Query" onkeydown="textSearchPress(event, '{{ active_project }}', '{{ active_logfile }}')" oninput='textSearchInput(event, {{ log_fields | tojson }})'>

                <button id="search-button" onclick="search('{{ active_project }}', '{{ active_logfile }}')">Search</button>
                <!-- <button>Date</button>-->

                <div id="text-search-suggestions" class="d-none"></div>

            </div>
            {% endif %}

            <!-- Select project to show logs for -->
            <div id="project-select-wrapper">
                <p>Project</p>
                <div id="project-select">
                    <select>
                        {% for project_id in projects %}
                        <option value="{{ project_id }}" {% if not loop.index0 %}selected {% endif %}onclick="window.location.href='{{ url_for('index.project', project_id=project_id) }}'">
                            {{ project_id }}
                        </option>
                        {% endfor %}
                    </select>
                </div>

                <br>

                <!-- Add project area -->
                <button onclick="showAddProject()">
                    Add Project
                </button>
        
                <div id="add-project-wrapper" class="d-none">
                    <form action="{{ url_for('index.add_project') }}" method="post">
                        <input name="project_id" placeholder="Project ID">
                        <input name="log_path" placeholder="Path to log folder">

                        <button>Add</button>
                        <button onclick="cancelAddProject(event)" type="button">
                            Cancel
                        </button>
                    </form>

                </div>
            </div>
        </div>

        {% if active_project %}
            <!-- Found log entries -->
            <div id="search-results-wrapper" class="d-none">
                <div id="search-results-list" class="d-none"></div>
                <div id="search-results-loading" class="loading-icon"></div>
                <div id="no-results-placeholder" class="d-none">No log entries found.</div>
                <div id="search-error" class="d-none">Error during search :(</div>
            </div>
        {% endif %}
    </div>
</body>
</html>

src/app/templates/login.html
<!DOCTYPE html>
<html>
{% include 'head.html' %}

<body>
    <div id="login-wrapper">
        <h1>Clog</h1>
        <form action="{{ url_for('login.sign_in') }}" method="POST">
            <input type="hidden" value="admin" name="user">
            <input type="password" name="pass">
            <input type="submit" value="Login" class="btn">
        </form>

        <p id="login-error-msg">{% if error %}{{ error }}{% endif %}</p>
    </div>
</body>
</html>